services:
  wos-danger-bot:
    image: ghcr.io/xmnsorsaadx-ux/wos-danger:latest
    container_name: wos-danger-bot
    volumes:
      - /opt/docker/wos/db/:/app/db
    restart: unless-stopped
    environment:
      - DISCORD_BOT_TOKEN=<your bot token here>